### ISSUE TITLE
miniZ keeps shutting down after mining for 30 mins, 1080ti rig

### ISSUE THREAD

**Issue by DonPalmTho** [miniZ-miner/miniZ#1] opened 2022-03-11 06:01 UTC
anyone can solve this issue?

**Comment by miniZ-miner** [comment] 2022-04-26 01:20
Hi DonPalmTho, sorry for late response. Are you still having this issue?
Could you share more information? OCs, PL, Algo, OS, and miniZ version?
Thanks. Cheers

**Comment by m0haz** [comment] 2022-05-16 07:20
> Hi DonPalmTho, sorry for late response. Are you still having this issue? Could you share more information? OCs, PL, Algo, OS, and miniZ version? Thanks. Cheers

I'm having a similar, possibly the same issue...

I get Cuda Error 77 Illegal Memory access line 300 on my Nvidia rig all the time.  Sometimes it will mine for 15 minutes and error, sometimes it will mine for 3 hours and give the error.  I have lowered my overclocks to 0 on all cards, but it seems to do better with higher overclocks for some reason...it will work longer before throwing the fatal error.  It isn't always the same GPUs related to the error either... Sometimes it will say GPU 0. Sometimes it will say GPU 2,3,6.. Sometimes other GPUs...It's never very consistent.  I am pulling my hair out here trying to figure out what's going on.... I increased my paging file to 64gb, no luck.  Reinstalled drivers, played with over clocks and lowered power, everything I can think of.

**Comment by miniZ-miner** [comment] 2022-11-07 20:59
Hi m0haz, is this issue solved with newer versions?

**Comment by m0haz** [comment] 2022-11-07 22:28
> Hi m0haz, is this issue solved with newer versions?

Hey there, my issue ended up not being software related at all.  I had a power supply  going bad and did not know it...even running my GPUs pulling far less power than they should or that the PSU could supply, these errors were likely due to dips/spikes in power.  After my PSU exploded and I replaced it, I never had another issue with miniZ

**Comment by miniZ-miner** [comment] 2022-11-07 23:38
Hi m0haz,
Good to know that you managed to find the cause, and it is working well now.
This may be usefull for someone else.
We'll close the issue now and we will use your report for future reference.
Thanks for using miniZ.
Cheers

**Closed** 2022-11-07 23:38 UTC
